# Part 1
import pathlib
L=[]
a=L.append

a("# 기능 명세서: phiGuard.js - PHI 마스킹 보안 가드 모듈")
a("")
a("**Feature Branch**: `PLAYG-1831-phi-guard`")
a("**Status**: Draft | **Date**: 2026-05-04")
a("**Ticket**: `PLAYG-1831` | **Type**: Detailed Design (SDS-3.12)")
a("**Input**: Jira 티켓 PLAYG-1831 상세 설계 요청")
a("")
a("---")
a("")
a("## User Scenarios & Testing")
a("")
a("### User Story 1 - PHI 필드 자동 마스킹 (Priority: P1) :dart: MVP")
a("- **설명**: DICOM 메타데이터 객체에서 환자 식별 정보(patientName, patientID, patientBirthDate)를 [REDACTED]로 자동 마스킹한다. 원본 값은 모듈 내부 WeakMap에 안전하게 보관되어 필요시 getPhiValue()로 조회할 수 있다.")
a("- **Why this priority**: 의료 소프트웨어에서 PHI 보호는 HIPAA 및 국내 개인정보보호법에 의거한 법적 필수 사항이며, 정보 유출은 HAZ-3.1 위험에 직결된다.")
a("- **Independent Test**: patientName과 patientID가 포함된 metadata 객체를 maskPhiFields()에 전달하여 두 필드 모두 [REDACTED]로 치환되었는지, getPhiValue()로 원본을 조회할 수 있는지 확인한다.")

a("- **Acceptance Scenarios**:")
a("  1. **Given** patientName=`홍길동`, patientID=`P001`, patientBirthDate=`19900101`인 metadata 객체이면, **When** maskPhiFields(metadata)를 호출하면, **Then** 세 필드 모두 `[REDACTED]`로 치환된다.")
a("  2. **Given** 마스킹이 완료된 metadata이면, **When** getPhiValue(metadata, `patientName`)을 호출하면, **Then** 원본 값 `홍길동`이 반환된다.")
a("  3. **Given** patientName만 존재하고 patientID/patientBirthDate가 누락된 metadata이면, **When** maskPhiFields(metadata)를 호출하면, **Then** patientName만 마스킹되고 나머지 필드는 그대로 유지된다.")
a("")
a("### User Story 2 - 원본 PHI 값 안전 조회 (Priority: P1) :dart: MVP")
a("- **설명**: 마스킹된 메타데이터에서 필요시 원본 PHI 값을 안전하게 조회할 수 있다. 조회는 PHI_FIELDS에 등록된 필드만 허용되며, 비인가 필드 조회는 undefined를 반환하여 차단한다.")
a("- **Why this priority**: 마스킹된 상태에서도 권한 있는 모듈(예: 리포트 생성)에서 원본 환자 정보가 필요할 수 있으므로 안전한 조회 경로가 필수적이다.")
a("- **Independent Test**: 마스킹 완료된 metadata 객체에서 getPhiValue()로 원본을 조회하고, 비 PHI 필드 조회 시 undefined 반환을 확인한다.")
a("- **Acceptance Scenarios**:")
a("  1. **Given** maskPhiFields()로 마스킹된 metadata이면, **When** getPhiValue(metadata, `patientName`)을 호출하면, **Then** 원본 환자 이름 문자열이 반환된다.")
a("  2. **Given** 마스킹된 metadata이면, **When** getPhiValue(metadata, `rows`)를 호출하면(비 PHI 필드), **Then** undefined가 반환되어 비인가 필드 조회가 차단된다. (추적: SEC-3)")
a("  3. **Given** maskPhiFields()를 거치지 않은 metadata이면, **When** getPhiValue(metadata, `patientName`)을 호출하면, **Then** undefined가 반환된다 (phiStore에 저장된 원본이 없음).")

a("")
a("### User Story 3 - null/비객체 입력 안전 처리 (Priority: P1) :dart: MVP")
a("- **설명**: null, undefined, 또는 객체가 아닌 값이 maskPhiFields()에 전달되어도 예외가 발생하지 않고 입력값을 그대로 반환한다.")
a("- **Why this priority**: 의료 소프트웨어의 안전 등급(Class A)에서 예외 발생 없는 견고한 입력 처리는 필수적이다.")
a("- **Independent Test**: null, undefined, 문자열, 숫자 값을 maskPhiFields()에 전달하여 예외 없이 입력값이 반환되는지 확인한다.")
a("- **Acceptance Scenarios**:")
a("  1. **Given** null 값이면, **When** maskPhiFields(null)을 호출하면, **Then** 예외 없이 null이 반환된다.")
a("  2. **Given** undefined 값이면, **When** maskPhiFields(undefined)을 호출하면, **Then** 예외 없이 undefined가 반환된다.")
a("  3. **Given** 문자열 `abc`이면, **When** maskPhiFields(`abc`)를 호출하면, **Then** 예외 없이 `abc`가 그대로 반환된다.")
a("")
a("### User Story 4 - 빈 문자열 및 undefined 값 마스킹 생략 (Priority: P2)")
a("- **설명**: PHI 필드 값이 undefined이거나 빈 문자열(``)인 경우 마스킹을 수행하지 않는다. DICOM 파일에서 해당 필드가 누락된 경우 기본값이 빈 문자열이므로, 마스킹하면 오히려 정보가 존재한다는 오해를 줄 수 있다.")
a("- **Why this priority**: 올바른 마스킹 정책 적합성이지만, 실제 정보 유출과는 무관하여 P2로 지정한다.")
a("- **Independent Test**: patientName이 `` 또는 undefined인 metadata에서 마스킹 후 해당 필드가 [REDACTED]가 아닌 원래 값 그대로 유지되는지 확인한다.")
a("- **Acceptance Scenarios**:")
a("  1. **Given** patientName이 빈 문자열(``)인 metadata이면, **When** maskPhiFields(metadata)를 호출하면, **Then** metadata.patientName이 `[REDACTED]`가 아닌 ``로 유지된다.")
a("  2. **Given** patientID가 undefined(필드 자체가 없음)인 metadata이면, **When** maskPhiFields(metadata)를 호출하면, **Then** metadata에 patientID 필드가 추가되지 않는다.")

a("")
a("### User Story 5 - 전체 PHI 값 일괄 조회 (디버그 전용) (Priority: P3)")
a("- **설명**: dumpPhiValues() 함수를 통해 모든 원본 PHI 값을 일괄 조회할 수 있다. 이 함수는 @internal 태그가 부여되어 배럴 파일에서 export되지 않으므로 프로덕션 UI에서 직접 접근할 수 없다.")
a("- **Why this priority**: 개발/디버깅 지원 기능으로 프로덕션 기능이 아니므로 P3로 지정한다.")
a("- **Independent Test**: 마스킹된 metadata 객체에서 dumpPhiValues()를 호출하여 모든 원본 PHI 필드가 포함된 객체가 반환되는지 확인한다.")
a("- **Acceptance Scenarios**:")
a("  1. **Given** maskPhiFields()로 마스킹된 metadata이면, **When** dumpPhiValues(metadata)를 호출하면, **Then** 모든 원본 PHI 값이 포함된 객체(예: `{patientName: ...`})가 반환된다.")
a("  2. **Given** maskPhiFields()를 거치지 않은 metadata이면, **When** dumpPhiValues(metadata)를 호출하면, **Then** 빈 객체 `{}`가 반환된다.")
a("")
a("### Edge Cases (엣지 케이스)")
a("- **EC-001**: metadata가 null인 경우 - 예외 없이 null 반환 (NFR-4)")
a("- **EC-002**: metadata가 undefined인 경우 - 예외 없이 undefined 반환 (NFR-4)")
a("- **EC-003**: metadata가 객체가 아닌 경우(숫자, 문자열, 불리언) - 그대로 반환 (NFR-4)")
a("- **EC-004**: PHI 필드 값이 undefined인 경우 - 마스킹 생략, phiStore에 저장하지 않음")
a("- **EC-005**: PHI 필드 값이 빈 문자열(``)인 경우 - 마스킹 생략, phiStore에 저장하지 않음")
a("- **EC-006**: getPhiValue()에 비 PHI 필드명 전달 - undefined 반환 (SEC-3)")
a("- **EC-007**: getPhiValue()에 마스킹되지 않은 metadata 전달 - undefined 반환")
a("- **EC-008**: 동일 metadata 객체에 maskPhiFields() 중복 호출 - 이미 [REDACTED]인 값을 원본으로 덮어씀 (설계상 허용: metadataParser에서는 1회만 호출됨)")
a("- **EC-009**: metadata 객체가 GC된 후 getPhiValue() 호출 - WeakMap 특성상 키가 사라져 undefined 반환 (메모리 안전성)")

a("")
a("---")
a("")
a("## Requirements")
a("")
a("### Functional Requirements (기능 요구사항)")
a("")
a("- **FR-001**: 시스템은 DICOM 메타데이터 객체에서 PHI 필드를 `[REDACTED]`로 마스킹하는 `maskPhiFields(metadata)` 함수를 제공해야 한다. 함수 시그니처: `maskPhiFields(metadata: Object|null|undefined) -> Object|null|undefined` (추적: FR-4.1, HAZ-3.1)")
a("- **FR-002**: 시스템은 PHI 마스킹 대상 필드를 `PHI_FIELDS` 상수 배열로 관리해야 한다. `PHI_FIELDS = ['patientName', 'patientID', 'patientBirthDate']`로, DICOM Tag (0010,0010), (0010,0020), (0010,0030)에 해당한다. (추적: FR-4.1, SEC-3)")
a("- **FR-003**: 시스템은 마스킹 문자열을 `PHI_MASK` 상수로 관리해야 한다. `PHI_MASK = '[REDACTED]'`. 향후 마스킹 정책 변경 시 단일 지점 수정으로 대응 가능해야 한다.")
a("- **FR-004**: maskPhiFields()는 metadata가 null, undefined, 또는 객체가 아닌 경우 입력값을 그대로 반환하고 예외를 발생시키지 않아야 한다. (추적: NFR-4)")
a("- **FR-005**: maskPhiFields()는 PHI 필드 값이 undefined이거나 빈 문자열(``)인 경우 마스킹을 생략해야 한다. (추적: FR-4.1)")
a("- **FR-006**: maskPhiFields()는 유효한 PHI 필드 값을 `[REDACTED]`로 치환하고, 원본 값을 phiStore(WeakMap)에 metadata 객체 참조를 키로 하여 저장해야 한다. (추적: FR-4.1, HAZ-3.1)")

a("- **FR-007**: 시스템은 마스킹된 메타데이터에서 원본 PHI 값을 안전하게 조회하는 `getPhiValue(metadata, field)` 함수를 제공해야 한다. 함수 시그니처: `getPhiValue(metadata: Object, field: string) -> string|undefined` (추적: FR-4.1)")
a("- **FR-008**: getPhiValue()는 field가 PHI_FIELDS에 포함되지 않은 경우 undefined를 반환하여 비인가 필드 조회를 차단해야 한다. (추적: SEC-3)")
a("- **FR-009**: getPhiValue()는 phiStore에 해당 metadata 키가 존재하지 않는 경우 undefined를 반환해야 한다. (추적: FR-4.1)")
a("- **FR-010**: 시스템은 모든 원본 PHI 값을 일괄 조회하는 `dumpPhiValues(metadata)` 함수를 제공해야 한다. 함수 시그니처: `dumpPhiValues(metadata: Object) -> Object`. 이 함수는 @internal로 분류되어 배럴 파일(index.js)에서 export되지 않는다.")
a("- **FR-011**: phiStore는 모듈 스코프의 `WeakMap<Object, Object>`이며, 외부에서 직접 접근할 수 없다. 원본 PHI 값의 유일한 저장소다.")
a("- **FR-012**: maskPhiFields()는 동일한 metadata 참조를 반환해야 한다 (새 객체 생성 없음). 이는 metadataParser.js에서 반환값 없이 사용할 수 있도록 한다.")

a("")
a("### Non-Functional Requirements (비기능 요구사항)")
a("")
a("- **NFR-001 (보안)**: PHI 원본 값은 phiStore(WeakMap)에만 저장되며, 모듈 외부에서 직접 접근할 수 없어야 한다. 원본 조회는 getPhiValue() 함수를 통해서만 가능하다. (추적: SEC-3, HAZ-3.1)")
a("- **NFR-002 (메모리 안전성)**: WeakMap을 사용하여 metadata 객체가 가비지 컬렉션될 때 원본 PHI 값도 자동으로 해제되어 메모리 누수가 발생하지 않아야 한다.")
a("- **NFR-003 (불변성)**: PHI_FIELDS 배열과 PHI_MASK 상수는 `const`로 선언되어 런타임 수정이 불가능해야 한다.")
a("- **NFR-004 (견고성)**: maskPhiFields()는 null, undefined, 비객체 입력에 대해 예외를 발생시키지 않고 안전하게 처리해야 한다. (추적: IEC 62304 Class A)")
a("- **NFR-005 (단일 책임)**: phiGuard.js는 PHI 마스킹과 원본 값 안전 보관만을 담당하며, 비즈니스 로직을 포함하지 않아야 한다. (IEC 62304 Class A)")
a("")
a("### Key Entities (핵심 데이터 모델)")
a("")
a("- **PHI_FIELDS**: `const` 배열. 마스킹 대상 필드명 목록. `['patientName', 'patientID', 'patientBirthDate']`. DICOM Tag (0010,0010), (0010,0020), (0010,0030)에 대응.")
a("- **PHI_MASK**: `const` 문자열. `'[REDACTED]'`. 마스킹 치환 문자열.")
a("- **phiStore**: `WeakMap<Object, Object>`. 원본 PHI 값을 객체 참조를 키로 하여 안전 보관. 모듈 내부 전용(export 되지 않음). metadata 객체 GC 시 원본 값도 자동 해제.")
a("- **DICOMMetadata**: createDICOMMetadata() 팩토리로 생성된 메타데이터 객체. phiGuard는 이 객체의 PHI 필드를 조작한다.")

a("")
a("### 연관 모듈 의존성")
a("")
a("| 모듈 | 함수/상수 | 역할 | 연관 SDS |")
a("|------|-----------|------|----------|")
a("| metadataParser.js | parseMetadata() | Step 8에서 maskPhiFields() 호출, PHI 마스킹 수행 | SDS-3.9 |")
a("| index.js (배럴) | export | maskPhiFields, getPhiValue만 공개 (dumpPhiValues 미노출) | - |")
a("| DICOMMetadata | createDICOMMetadata() | 메타데이터 객체 팩토리 (phiGuard 소비 대상) | SDS-3.10 |")
a("")
a("---")
a("")
a("## Success Criteria")
a("")
a("### Measurable Outcomes (측정 가능한 지표)")
a("")
a("- **SC-001**: patientName이 포함된 metadata 마스킹 후 `metadata.patientName === '[REDACTED]'`이 참이다. (TC-12.1)")
a("- **SC-002**: patientID가 포함된 metadata 마스킹 후 `metadata.patientID === '[REDACTED]'`이 참이다. (TC-12.2)")
a("- **SC-003**: 마스킹 후 getPhiValue(metadata, `patientName`) 호출 시 원본 환자 이름이 정확히 반환된다. (TC-12.3)")
a("- **SC-004**: getPhiValue(metadata, `rows`) 호출 시(비 PHI 필드) undefined가 반환되어 비인가 조회가 차단된다. (TC-12.4)")
a("- **SC-005**: 빈 문자열(``)인 PHI 필드는 마스킹되지 않고 그대로 유지된다. (TC-12.5)")
a("- **SC-006**: maskPhiFields(null) 호출 시 예외 없이 null이 반환된다. (TC-12.6)")
a("- **SC-007**: PHI_MASK와 PHI_FIELDS 상수가 런타임에서 수정 불가능하다. (NFR-003)")
a("- **SC-008**: metadata 객체가 GC된 후 phiStore에서 원본 값이 자동 해제된다. (NFR-002)")
